### ISSUE TITLE
[Epic] 부가 화면 구성

### ISSUE THREAD

**Issue by L2HYUNN** [dnd-side-project/dnd-7th-4-frontend#14]
## Description
부가 화면 구성하기

## Initiative / goal
서비스에 이용되는 부가 화면을 구성한다.
구성해야하는 부가 화면 목록은 다음과 같다.

1. 로그인 / 회원 가입 화면 ( 카카오톡 ) 
2. 알림 설정 / 알림 안내 등 알림 관련 화면
3. 슬라이드 메뉴 및 설정( 서비스, 회원 ) 관련 화면

## Hypothesis
#11 #12 #13 

### 기능
- [x] 카카오톡 회원가입 및 로그인을 할 수 있다. 
- [x] 알림을 설정하고 안내 및 확인 할 수 있다.
- [x] 슬라이드 메뉴를 통해 설정 관련 화면으로 이동할 수 있다.

### 스타일
- [x] PC 버전 디자인을 적용할 수 있다.
- [x] 모바일 버전 디자인을 적용할 수 있다.

## Stakeholders
- Designers ( 최지원, 이주현 )

## Timeline
2022.08.14
