### ISSUE TITLE
[Epic] 메인 화면 리팩토링

### ISSUE THREAD

**Issue by ndnv819** [dnd-side-project/dnd-7th-4-frontend#22]
## Description
메인 화면 리팩토링

## Initiative / goal
메인 화면과 관련된 페이지들의 리팩토링을 진행한다.

## Hypothesis
https://www.notion.so/team-project22/FE-8-12-e1876460b5f44f29bf0efb6ea830dc58

## Acceptance criteria and must have scope
기능
- [ ] 외부함수를 `useCallback`이나 `useMemo`로 감싸주었는가. 
- [ ] 상황에 따른 render 중복을 막기 위해 `useCallback`을 사용하였는가.
- [ ] 컴포넌트 함수에 `memo()`를 사용하였는가.
- [ ] 에러 케이스와 로직을 명확하게 분리하였는가.
- [ ] readonly 변수들의 마지막에 `as const`를 적어주었는가

## Stakeholders
Designers ( 최지원, 이주현 )

## Timeline
2022.08.22
