### ISSUE TITLE
[Epic] 메인 화면 구성

### ISSUE THREAD

**Issue by L2HYUNN** [dnd-side-project/dnd-7th-4-frontend#3]
## Description
메인 화면 구성하기 

## Initiative / goal
직관적인 날씨 확인을 위한 메인 화면을 구성한다.
메인(홈) 화면에 연관된 모든 기능을 구성한다. 

## Hypothesis
#2

### 기능
- [x] 실시간으로 날씨 데이터를 확인할 수 있다.
- [x] 다양한 페이지로 이동할 수 있다. 
- [x] 설정된 위치에 따른 날씨 정보를 확인할 수 있다.  
- [x] 상세한 날씨 정보를 확인할 수 있다.

### 스타일
- [x] PC 버전 디자인을 적용할 수 있다.
- [x] 모바일 버전 디자인을 적용할 수 있다.  

## Stakeholders
- Designers ( 최지원, 이주현 ) 

## Timeline
2022.08.07
