### ISSUE TITLE
[Epic] 메인 화면 고도화

### ISSUE THREAD

**Issue by L2HYUNN** [dnd-side-project/dnd-7th-4-frontend#32]
## Description
메인 화면을 고도화 합니다.

## Initiative / goal
API 연결을 통해 서버와의 통신 기능을 구현합니다.
제작된 HI-FI를 바탕으로 CSS 작업을 완료합니다.

## Hypothesis
#2 

### 기능
- [ ] API를 통해 날씨 데이터를 확인할 수 있다.
- [ ] API를 통해 위치 데이터를 확인할 수 있다.
- [ ] API를 통해 부가 날씨 데이터를 확인할 수 있다.
- [ ] API를 통해 받은 데이터를 적절하게 관리할 수 있다. ( Client / Sever )  

### 스타일
- [ ] 디자인 시스템을 적용할 수 있다.
- [ ] Hi-fi에 맞는 디자인을 적용할 수 있다. 

## Stakeholders
- Designers ( 최지원, 이주현 )

## Timeline
- 2022.08.22
