### ISSUE TITLE
[Epic] 보조 화면 고도화

### ISSUE THREAD

**Issue by L2HYUNN** [dnd-side-project/dnd-7th-4-frontend#33]
## Description
보조 화면을 고도화 합니다.

## Initiative / goal
API 연결을 통해 서버와의 통신 기능을 구현합니다.
제작된 HI-FI를 바탕으로 CSS 작업을 완료합니다.

## Hypothesis
#11 #12 #13 

### 기능
- [ ] 카카오톡 로그인 기능을 구현할 수 있다.
- [ ] 슬라이드 메뉴와 관련된 기능을 구현할 수 있다.
- [ ] 알림 화면 관련된 기능을 구현할 수 있다.
- [ ] 상태 관리를 통해 정확하게 할 수 있다. ( Client / Server ) 

### 스타일
- [ ] 디자인 시스템을 적용할 수 있다.
- [ ] Hi-fi에 맞는 디자인을 적용할 수 있다. 

## Stakeholders
- Designers ( 최지원, 이주현 )

## Timeline
- 2022.08.22
